# SPDX-License-Identifier: GPL-3.0-only
# Original at https://github.com/tyron12233/CodeAssist/blob/main/.github/workflows/build-apk.yml
# Changes: Minor adjustments, removal of Cancel previous runs step, but every change can be found with a simple diff.

name: Android CI

on:
  push:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'build-logic/**'
      - 'kotlinc/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
  pull_request:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'build-logic/**'
      - 'kotlinc/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
  workflow_dispatch:

jobs:
  build:
    name: Build debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build debug APK with minApi 26
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleMinApi26Debug

      - name: Upload debug APK with minApi 26
        uses: actions/upload-artifact@v3
        with:
          name: apk-minApi26-debug
          path: app/build/outputs/apk/minApi26/debug

      - name: Build debug APK with minApi 21
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleMinApi21Debug

      - name: Upload debug APK with minApi 21
        uses: actions/upload-artifact@v3
        with:
          name: apk-minApi21-debug
          path: app/build/outputs/apk/minApi21/debug
